// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "17eacf54-976e-4ce9-8cf1-959126a155e7");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1656833587);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1656833827);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1656833354);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1656835031);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1656833227);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1656833467);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1656833257);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1656833707);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 19092);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1656742828);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{85343baa-399f-436d-9b0a-94f86aa18d9e}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "yandex");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://yandex.com\",\"label\":\"@яндекс\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1656833199858");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1656854799858");
user_pref("browser.search.region", "RU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210927121355");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1656835031");
user_pref("browser.slowStartup.averageTime", 3254);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20210927121355");
user_pref("browser.startup.homepage_override.mstone", "78.15.0");
user_pref("browser.startup.lastColdStartupCheck", 1656835030);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 1);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1656742834018");
user_pref("distribution.iniFile.exists.appversion", "78.15.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "c307d15a33da4e65b597327d5864ebf4");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1656833587);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210927121355");
user_pref("extensions.lastAppVersion", "78.15.0");
user_pref("extensions.lastPlatformVersion", "78.15.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{fefeca07-ddae-4ef7-b752-da1bfb10cbaf}\",\"addons\":{\"proxy-failover@mozilla.com\":{\"version\":\"1.0.1\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"36cf5399-3c3b-43ac-a52e-1900e1515d87\",\"formautofill@mozilla.org\":\"999609db-2b90-4e3f-ab27-32294cacce55\",\"screenshots@mozilla.org\":\"7359ba00-b85b-48d2-8103-335a2f18cd1a\",\"webcompat-reporter@mozilla.org\":\"66e0fdfe-c99d-4fb9-ac4a-f1a5339ea239\",\"webcompat@mozilla.org\":\"a6a0b9fd-d4e0-4cc6-ada9-0d46d4f9d4a7\",\"default-theme@mozilla.org\":\"d679d1a9-fa99-4772-bb5f-972c7bdd343b\",\"google@search.mozilla.org\":\"43a46918-9b04-45c9-8ae4-704ce1d6596f\",\"wikipedia@search.mozilla.org\":\"295b4523-f443-426f-a305-18fcc030646d\",\"yandex@search.mozilla.org\":\"f59f7cab-9ee3-41d8-a975-726ad954ebb9\",\"ddg@search.mozilla.org\":\"c3475011-70a1-4b01-a011-4e31b5ba34e2\",\"priceru@search.mozilla.org\":\"da24bb56-f025-4e9e-ab85-ea5a4358d17b\",\"mailru@search.mozilla.org\":\"481792ab-c4d4-469d-a60e-33befd335d01\",\"ozonru@search.mozilla.org\":\"9af248a8-baa1-4652-adb3-afd984938230\",\"proxy-failover@mozilla.com\":\"a4565d6c-81d6-432f-8b7b-c5384bb9d397\"}");
user_pref("idle.lastDailyNotification", 1656833463);
user_pref("media.gmp-manager.buildID", "20210927121355");
user_pref("media.gmp-manager.lastCheck", 1656833304);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1656833463);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1656833303);
user_pref("security.remote_settings.intermediates.checked", 1656833303);
user_pref("security.sandbox.content.tempDirSuffix", "80b143f1-c116-4cb1-833d-18f7b16cfbc6");
user_pref("security.sandbox.plugin.tempDirSuffix", "3fe72e7a-6719-4ad9-9964-6fb0a09b1c01");
user_pref("services.blocklist.addons-mlbf.checked", 1656833303);
user_pref("services.blocklist.gfx.checked", 1656833303);
user_pref("services.blocklist.plugins.checked", 1656833303);
user_pref("services.settings.clock_skew_seconds", -1683);
user_pref("services.settings.last_etag", "\"1656831433009\"");
user_pref("services.settings.last_update_seconds", 1656835149);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1656833303);
user_pref("services.settings.main.cfr.last_check", 1656833303);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1656833303);
user_pref("services.settings.main.hijack-blocklists.last_check", 1656833303);
user_pref("services.settings.main.language-dictionaries.last_check", 1656833303);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1656833303);
user_pref("services.settings.main.public-suffix-list.last_check", 1656833303);
user_pref("services.settings.main.search-config.last_check", 1656833303);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1656833303);
user_pref("services.settings.main.sites-classification.last_check", 1656833303);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1656833303);
user_pref("services.settings.main.whats-new-panel.last_check", 1656833303);
user_pref("services.settings.security.onecrl.checked", 1656833303);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1656833463);
user_pref("toolkit.startup.last_success", 1656835026);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210927121355");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
